### ISSUE TITLE
Move repository to the githulks organization.

### ISSUE THREAD

**Issue by 3rd-Eden** [satish-ravi/githulk-test#1]
Hey, I wonder if you could move this repository to the githulks organization? So we have all the test repo's and code under a single entity in GitHub.

https://github.com/githulks

**Comment by satish-ravi** [comment]
Sure, but I don't think I have access to the githulks organization. Can you provide me access?

**Comment by 3rd-Eden** [comment]
I've send you an inivte.

**Comment by satish-ravi** [comment]
Thanks, made a PR to update repo name in tests. 
https://github.com/githulks/githulk/pull/42
